### ISSUE TITLE
Permission nodes?

### ISSUE THREAD

**Issue by kimnthorstensen** [DuooIncc/UpgradeUI#2]
Hi!

Awesome plugin! I was wondering if you could add support for permission nodes?

Best regards,
Kim

**Comment by DuooIncc** [comment]
Hey! Sorry it wasn't very clear.

The latest update to the README.md file includes everything you should need!

**Comment by kimnthorstensen** [comment]
No problem at all! Thank you 😊

Best regards,
Kim

tir. 8. okt. 2019, 20:24 skrev DuooIncc <notifications@github.com>:
